name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name : Check if node is installed
      run: |
            if command -v node >/dev/null 2>&1; then
              echo "Node.js is installed."
            else
              echo "Node.js is not installed."
            fi
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: |
        docker build -t reactdev:latest .
    - name: Push Docker image
      run: |
        docker tag reactdev:latest {DOCKERHUB_USERNAME}/reactdev:latest
        docker push {DOCKERHUB_USERNAME}/reactdev:latest